version: "3"
output: interleaved
dotenv: [".env.local"]

includes:
  index: https://raw.githubusercontent.com/livekit-examples/index/main/taskfile.yaml

tasks:
  post_create:
    desc: "Runs after this template is instantiated as a Sandbox or Bootstrap"
    cmds:
      - task: index:help_setup_python_uv
      - task: index:help_deploy_agent

  install:
    desc: "Bootstrap application for local development"
    cmds:
      - task: index:install_python_uv

  dev:
    interactive: true
    cmds:
      - task: index:dev_python_uv
